package blake.nestedBox

class TestRunner { // BOXES MUST BE NESTED IN A DFS METHOD (follow each nesting to its end before backtracking)
    fun runTest1() {
        var masterBox = Box('h') // Alignment of a box with no children doesn't matter, can be 'h' or 'v'
        masterBox.resetGrid() // must reset grid before attempting to print to allow multiple tests to be run
        masterBox.printGrid()
    }

    fun runTest2() {
        var masterBox = Box('h')
        var childBox1 = Box('v')
        var childBox2 = Box('h')
        var childBox3 = Box('v')
        var childBox4 = Box('v')
        var childBox5 = Box('h')
        var childBox6 = Box('h')
        var childBox7 = Box('h')
        var childBox8 = Box('h')
        var childBox9 = Box('v')
        var childBox10 = Box('v')
        var childBox11 = Box('v')
        masterBox.nestBox(childBox1)
        childBox1.nestBox(childBox2)
        childBox2.nestBox(childBox3)
        childBox2.nestBox(childBox4)
        childBox1.nestBox(childBox5)
        childBox1.nestBox(childBox6)
        masterBox.nestBox(childBox7)
        masterBox.nestBox(childBox8)
        masterBox.nestBox(childBox9)
        childBox9.nestBox(childBox10)
        childBox9.nestBox(childBox11)
        masterBox.resetGrid()
        masterBox.printGrid()
    }

    fun runTest3() {
        var masterBox = Box('v')
        var childBox1 = Box('h')
        var childBox2 = Box('v')
        var childBox3 = Box('v')
        var childBox4 = Box('v')
        var childBox5 = Box('h')
        var childBox6 = Box('h')
        var childBox7 = Box('h')
        var childBox8 = Box('h')
        var childBox9 = Box('h')
        var childBox10 = Box('v')
        var childBox11 = Box('v')
        masterBox.nestBox(childBox1)
        childBox1.nestBox(childBox2)
        childBox2.nestBox(childBox3)
        childBox2.nestBox(childBox4)
        childBox1.nestBox(childBox5)
        childBox1.nestBox(childBox6)
        masterBox.nestBox(childBox7)
        masterBox.nestBox(childBox8)
        masterBox.nestBox(childBox9)
        childBox9.nestBox(childBox10)
        childBox9.nestBox(childBox11)
        masterBox.resetGrid()
        masterBox.printGrid()
    }

    fun runTest4() {
        var masterBox = Box('h')
        var childBox1 = Box('h')
        var childBox2 = Box('h')
        var childBox3 = Box('h')
        var childBox4 = Box('h')
        masterBox.nestBox(childBox1)
        childBox1.nestBox(childBox2)
        childBox2.nestBox(childBox3)
        childBox3.nestBox(childBox4)
        masterBox.resetGrid()
        masterBox.printGrid()
    }

    fun runTest5() {
        var masterBox = Box('h')
        var childBox1 = Box('v')
        var childBox2 = Box('v')
        var childBox3 = Box('v')
        var childBox4 = Box('v')
        var childBox5 = Box('v')
        var childBox6 = Box('v')
        var childBox7 = Box('v')
        var childBox8 = Box('v')
        var childBox9 = Box('v')
        var childBox10 = Box('v')
        var childBox11 = Box('v')
        var childBox12 = Box('v')
        masterBox.nestBox(childBox1)
        childBox1.nestBox(childBox2)
        childBox1.nestBox(childBox3)
        childBox1.nestBox(childBox4)
        masterBox.nestBox(childBox5)
        childBox5.nestBox(childBox6)
        childBox5.nestBox(childBox7)
        childBox5.nestBox(childBox8)
        masterBox.nestBox(childBox9)
        childBox9.nestBox(childBox10)
        childBox9.nestBox(childBox11)
        childBox9.nestBox(childBox12)
        masterBox.resetGrid()
        masterBox.printGrid()
    }
}